// Generated by CoffeeScript 1.10.0
import { PrivateKey } from 'Bitcore';
var address, privateKey, privateKeyWif, store;

store = localStorage;

privateKey = null;

privateKey = store.privateKey ? new PrivateKey(store.privateKey) : (privateKey = new PrivateKey, privateKeyWif = privateKey.toWIF(), store.privateKey = privateKeyWif, console.log('Private key saved successfully!'), console.log('Refresh the page or check your \'Resources > Local Storage\' from the developer tools'));

address = privateKey.toAddress().toString();

export privateKey, address;
