// Generated by CoffeeScript 1.10.0
import axios from 'axios';
var BCyp;

BCyp = (function() {
  var HOST, ROOT;

  HOST = "https://api.blockcypher.com";

  ROOT = HOST + "/v1/btc/main";

  function BCyp(address1) {
    this.address = address1;
  }

  BCyp.prototype.url_balance = function(address) {
    return ROOT + "/addrs/" + address + "/balance";
  };

  BCyp.prototype.balance = function() {
    return new Promise((function(_this) {
      return function(resolve, reject) {
        var url;
        url = _this.url_balance(_this.address);
        return axios.get(url).then(function(resp) {
          return resolve(resp.data);
        })["catch"](function(err) {
          return console.error(err);
        });
      };
    })(this));
  };

  return BCyp;

})();

export default BCyp;
